services:
    # -----------------------------
    # Wikidata Query Service
    # -----------------------------

    wdqs:
        image: wikibase/wdqs:1
        command: /runBlazegraph.sh
        depends_on:
            wikibase:
                condition: service_healthy
        restart: unless-stopped
        # Set number of files ulimit high enough, otherwise blazegraph will abort with:
        # library initialization failed - unable to allocate file descriptor table - out of memory
        # Appeared on Docker 24.0.5, containerd 1.7.9, Linux 6.6.6, NixOS 23.11
        ulimits:
            nofile:
                soft: 32768
                hard: 32768
        volumes:
            - wdqs-data:/wdqs/data
            - $W4R_INIT_FOLDER/config/wdqs/prefixes.conf:/wdqs/prefixes.conf
            - $W4R_INIT_FOLDER/config/wdqs/allowlist.txt:/wdqs/allowlist.txt
        healthcheck:
            test: curl --silent --fail localhost:9999/bigdata/namespace/wdq/sparql
            interval: 10s
            start_period: 2m
        labels:
            - "traefik.enable=false"

    wdqs-updater:
        image: wikibase/wdqs:1
        command: /wdqs/runUpdate.sh #-h http://wdqs:9999 -- -s 20000211170100  --wikibaseUrl $W4R_FULL_SERVER_NAME --conceptUri $W4R_FULL_SERVER_NAME  --entityNamespaces 120,122 -d 2 #/runUpdate.sh --start 20000101010000 --init  --apiPath /api.php
        #command: tail -F anything
        depends_on:
            wdqs:
                condition: service_healthy
        restart: unless-stopped
        # Set number of files ulimit high enough, otherwise blazegraph will abort with:
        # library initialization failed - unable to allocate file descriptor table - out of memory
        # Appeared on Docker 24.0.5, containerd 1.7.9, Linux 6.6.6, NixOS 23.11
        ulimits:
            nofile:
                soft: 32768
                hard: 32768
        volumes:
            - wdqs-data:/wdqs/data
        labels:
            - "traefik.enable=false"
        user: root
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    wdqs-proxy:
        image: wikibase/wdqs-proxy:1
        environment:
            - PROXY_PASS_HOST=wdqs:9999
        depends_on:
            wdqs:
                condition: service_healthy
        restart: unless-stopped

    wdqs-frontend:
        build:
            context: ${WDQS_FRONTEND_CONTAINER}
            args:
                WIKIBASE_SCHEME: ${W4R_SCHEME}
                WIKIBASE_ADDRESS: ${W4R_SERVER_NAME}
                WIKIBASE_CONCEPT: ${W4R_SERVER_NAME}
                WIKIBASE_NAME: ${W4R_MW_WIKI_NAME}
                CUSTOM_CONFIG_QUERY: ${W4R_WDQS_FRONTEND_SERVER_NAME}
        labels:
            - "traefik.http.routers.wdqs-frontend.rule=Host(`${W4R_WDQS_FRONTEND_SERVER_NAME}`)"
        restart: always
        volumes:
            - ./nginx/wdqs-frontend.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - wdqs-proxy
        networks:
            default:
                aliases:
                    - ${W4R_WDQS_FRONTEND_SERVER_NAME}
        environment:
            - WIKIBASE_HOST=${W4R_SERVER_NAME}
            - WDQS_HOST=wdqs-proxy
        healthcheck:
            test: curl --silent --fail localhost
            interval: 10s
            start_period: 2m
        ports:
            - "8900:80"

volumes:
    wdqs-data:
