services:
  redis:
    image: redis:alpine
  mongo:
    image: mongo:6.0
  server:
    image: registry.gitlab.com/nfdi4culture/ta1-data-enrichment/kompakkt-server/refactor:latest
    restart: always
    depends_on:
      - redis
      - mongo
    labels:
      - "traefik.http.routers.server.rule=Host(`manorhouses.tibwiki.io`) && PathPrefix(`/server`)"
      - "traefik.http.services.server.loadbalancer.server.port=8080"

  repo:
    image: registry.gitlab.com/nfdi4culture/ta1-data-enrichment/kompakkt-repo/refactor:latest
    depends_on:
      - redis
      - mongo
    labels:
      - "traefik.http.routers.repo.rule=Host(`manorhouses.tibwiki.io`)"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  viewer:
    image: registry.gitlab.com/nfdi4culture/ta1-data-enrichment/kompakkt-viewer/refactor:latest
    depends_on:
      - redis
      - mongo
    labels:
      - "traefik.http.routers.viewer.rule=Host(`manorhouses.tibwiki.io`) && PathPrefix(`/viewer`)"
      - "traefik.http.services.viewer.loadbalancer.server.port=80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf