services:
  # -----------------------------
  # Control service
  # -----------------------------
  # used for wiki init tasks like custom scripts for data insert

  control:
    build:
      context: .
      dockerfile: docker/control.Dockerfile
      args:
        W4R_CUSTOM_INIT_PYTHON_SCRIPT: ${W4R_CUSTOM_INIT_PYTHON_SCRIPT}
        W4R_INIT_FOLDER: ${W4R_INIT_FOLDER}
    depends_on:
      wikibase:
        condition: service_healthy
    environment:
      W4R_MW_ADMIN_USER: ${W4R_MW_ADMIN_USER}
      W4R_MW_ADMIN_PASS: ${W4R_MW_ADMIN_PASS}
      W4R_FULL_SERVER_NAME: ${W4R_FULL_SERVER_NAME}
      W4R_DATA_MODEL_SCRIPT_URL: ${W4R_DATA_MODEL_SCRIPT_URL}
      W4R_DATA_MODEL_FILE_URL: ${W4R_DATA_MODEL_FILE_URL}
    volumes:
      - $W4R_CUSTOM_INIT_PYTHON_SCRIPT:/app/custom_init.py
      - $W4R_INIT_FOLDER/scripts/model.ttl:/app/model.ttl
      - $W4R_INIT_FOLDER/scripts/formatterids.txt:/app/formatterids.txt
    volumes_from:
      - wikibase
    #restart: unless-stopped
    labels:
      - "traefik.enable=false"
