server {
    listen 443 ssl;
    server_name kompakkt.local;
    resolver 127.0.0.11 valid=5m;
    include mime.types;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    location / {
        proxy_pass http://repo:4200;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    #Every time we get a Q Number, we redirect to wb.$host/wiki/Item:QNumber
    location ~ ^/Q[0-9]+ {
        rewrite ^/(.*)$ http://wb.$host/wiki/Item:$1 permanent;
    }

    location /viewer/ {
        if_modified_since off;
        add_header Last-Modified "";
        proxy_pass http://viewer:8100;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    location /server/ {
        # Server handles compression on its own
        gzip off;
        # 1GB size limit for server
        client_max_body_size 1024m;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://server:8080/;
    }
}

server {
    listen 80;
    server_name kompakkt.local;
    return 301 https://$host$request_uri;
}



server {
    listen 80;
    server_name wb.kompakkt.local;
    return 301 https://$host$request_uri;
}
# Existing server block for HTTPS
server {
    listen 443 ssl;
    server_name wb.kompakkt.local;
    resolver 127.0.0.11 valid=5m;
    include mime.types;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    
    location / {
        proxy_pass http://wikibase;
    }
}

server {
    listen 80;
    server_name reconcile.wb.kompakkt.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name reconcile.wb.kompakkt.local;
        resolver 127.0.0.11 valid=5m;
    include mime.types;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    location / {
        proxy_pass http://openrefine-wikibase:8000;
    }
}

server {
    listen 80;
    server_name query.wb.kompakkt.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name query.wb.kompakkt.local;
    resolver 127.0.0.11 valid=5m;
    include mime.types;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    
    location / {
        proxy_pass http://wdqs-frontend;
    }
}