# Main server configuration for HTTP
server {
    include mime.types;
    resolver 127.0.0.11 valid=5m;

    # Common proxy headers
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto "https";

    location / {
        proxy_pass http://repo;
    }

    location /viewer/ {
        # Rewrite necessary for correct functioning of the viewer app
        rewrite ^/viewer/(.*)$ /$1 break;
        proxy_pass http://viewer;
    }

    location /server/ {
        # Server specific configurations
        gzip off;
        client_max_body_size 1024m;

        # Necessary rewrite for server app routing
        rewrite ^/server/(.*)$ /$1 break;
        proxy_pass http://server:8080;
    }

    # Redirect Q Numbers to the wikibase server
    location ~ ^/Q[0-9]+ {
        rewrite ^/(.*)$ http://wb.$host/wiki/Item:$1 redirect;
    }
}