server {
    listen       80;
    server_name  wdqs-frontend;

    # Add this new location block for /sparql
    location /sparql {
        proxy_pass http://wdqs:9999/bigdata/namespace/wdq/sparql;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /proxy/wikibase {
        rewrite /proxy/wikibase/(.*) /$1 break;
        proxy_pass http://wikibase:80;
    }

    location /proxy/wdqs {
        rewrite /proxy/wdqs/(.*) /$1 break;
        proxy_pass http://wdqs:9999/;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
